### ISSUE TITLE
Error opening CRE files in the GemRB demo

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#138]
With the new release, the game type popup seems to work nicely. If I choose something odd, NI crashes, but when I choose tob, like we were faking before, it loads normally. All fine up to here. However, when I try to open a CRE file, it errors out and displays nothing.

```
java.lang.NullPointerException
        at org.infinity.datatype.IdsBitmap.addIdsMapEntry(Unknown Source)
        at org.infinity.resource.Effect2.readCommon(Unknown Source)
        at org.infinity.resource.Effect2.read(Unknown Source)
        at org.infinity.resource.AbstractStruct.<init>(Unknown Source)
        at org.infinity.resource.AbstractStruct.<init>(Unknown Source)
        at org.infinity.resource.Effect2.<init>(Unknown Source)
        at org.infinity.resource.cre.CreResource.getPrototypes(Unknown Source)
        at org.infinity.gui.StructViewer.<init>(Unknown Source)
        at org.infinity.resource.AbstractStruct.makeViewer(Unknown Source)
/.../
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Exception in thread "AWT-EventQueue-0"
 java.lang.NullPointerException
        at org.infinity.datatype.AbstractBitmap.toString(Unknown Source)
        at org.infinity.datatype.AbstractBitmap.toString(Unknown Source)
        at org.infinity.gui.ViewerUtil.addLabelFieldPair(Unknown Source)
        at org.infinity.gui.ViewerUtil.addLabelFieldPair(Unknown Source)
        at org.infinity.resource.cre.Viewer.makeMiscPanel(Unknown Source)
        at org.infinity.resource.cre.Viewer.makeMainPanel(Unknown Source)
        at org.infinity.resource.cre.Viewer.<init>(Unknown Source)
        at org.infinity.resource.cre.CreResource.getViewerTab(Unknown Source)
        at org.infinity.gui.StructViewer.<init>(Unknown Source)
        at org.infinity.resource.AbstractStruct.makeViewer(Unknown Source)
/.../
        at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
/.../
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Looks like it requires slots.ids, which is not present:
https://github.com/NearInfinityBrowser/NearInfinity/blob/6d0d1a587866bfba790820f15a807e81740d031c/src/org/infinity/resource/Effect2.java#L116-L117

When I add an empty one it avoid the first null deref, but the second persists.

**Comment by Argent77** [comment]
Could you please run the NI binary attached to [this comment](https://github.com/NearInfinityBrowser/NearInfinity/issues/137#issuecomment-830780147) and post the stack trace? It helps me to narrow down the problems.

**Comment by lynxlynxlynx** [comment]
For the first problem I correctly identified the spot, while for the second the end part is:
```
        at org.infinity.datatype.AbstractBitmap.toString(AbstractBitmap.java:359)
        at org.infinity.datatype.AbstractBitmap.toString(AbstractBitmap.java:283)
        at org.infinity.gui.ViewerUtil.addLabelFieldPair(ViewerUtil.java:115)
        at org.infinity.gui.ViewerUtil.addLabelFieldPair(ViewerUtil.java:95)
        at org.infinity.resource.cre.Viewer.makeMiscPanel(Viewer.java:46)
```

**Comment by Argent77** [comment]
Thanks. It's most likely an uninitialized map instance. Try this: [NearInfinity-missing-resref-fix.zip](https://github.com/NearInfinityBrowser/NearInfinity/files/6411712/NearInfinity-missing-resref-fix.zip)

I couldn't reproduce the second trace log, so I don't know whether it's covered by this fix as well.

**Comment by lynxlynxlynx** [comment]
Yes, that fix is good and NI is graceful about the things it doesn't understand — the new GUI works regardless.
