### ISSUE TITLE
Wav exception when trying to play is fatal

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#143]
Some of the iwd2 wavs throw and NI can't recover from that:
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
        at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:503)
        at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:119)
        at org.infinity.resource.sound.AudioPlayer.play(Unknown Source)
        at org.infinity.resource.sound.SoundResource.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
An example is either EFF_P22A or EFF_P21C.

This report is not about adding further support, but just handling errors gracefully. I have to force-kill NI when it happens, destroying the whole session.

**Comment by Argent77** [comment]
Thanks. The specified error is hardware-specific, so I couldn't test it. However, the blocking issue may also happen with other audio-related errors.

This commit should fix the issue: Argent77/NearInfinity@6281272

**Comment by lynxlynxlynx** [comment]
Cool, I'll just believe it, but if you want I can retest once a build is available.

**Comment by Argent77** [comment]
I have successfully tested with a different error. But if you're able to trigger the same error as before, then I'd be interested in the result.
