### ISSUE TITLE
Search read error

### ISSUE THREAD

**Issue by burner1024** [NearInfinityBrowser/NearInfinity#169]
I get a lot of read errors using advanced search, but when I open the same file, no errors are reported.
What could be the issue?

Example
```
Error reading YSFIRE01.CRE
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.infinity.resource.ResourceFactory.getResource(Unknown Source)
	at org.infinity.resource.ResourceFactory.getResource(Unknown Source)
	at org.infinity.search.advanced.AdvancedSearchWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
![Captura desde 2023-11-19 00-50-51](https://github.com/NearInfinityBrowser/NearInfinity/assets/1279852/6517fa77-fb95-4b83-a835-7a47984a3596)

[YSFIRE01.CRE.zip](https://github.com/NearInfinityBrowser/NearInfinity/files/13401111/YSFIRE01.CRE.zip)

NI v2.4-20230729

**Comment by Argent77** [comment]
Is this the whole stacktrace? There are usually additional "Caused by" exceptions listed for that kind of exception.

Could you also provide a repro case?

**Comment by Argent77** [comment]
Nevermind, I found the error. It looks like this is caused by the "Nimbus" Look&Feel UI theme if NI is invoked by a more recent Java version. That UI theme was always incomplete, even in Java 8 (hence the warning message in the Preferences dialog), but it seems to be completely broken now. I'll remove this option in the next release.

**Comment by burner1024** [comment]
Eh, bye-bye Nimbus :).
